version: '3.8'  # Specifies the version of Docker Compose

services:  # Defines the services to be created in the Docker Compose environment.
  
  db: 
    image: postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:  # Mounts a volume to persist database data between restarts.
      - postgres_data:/var/lib/postgresql/data  # Maps the `postgres_data` volume to the PostgreSQL data directory.
    ports: 
      - '5432:5432'
    restart: always  # Automatically restarts the container if it stops.

  web: 
    build: .
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env  # Loads environment variables from the `.env` file.
    volumes:  # Mounts a volume to link the application code with the container.
      - .:/app  # Maps the current directory to the `/app` directory inside the container.
    ports: 
      - '8000:8000' 
    depends_on:
      - db  # Specifies that the web service depends on the db service.
    restart: always  # Automatically restarts the container if it stops.

  test:  # New test service
    build: .
    command: sh -c "python manage.py test"
    env_file:
      - .env
    depends_on:
      - db
    restart: "no"

volumes:  # Defines named volumes to persist data.
  postgres_data:
